import type { EtatSurface, Form, Participant, Points, PV, Releves } from "./types";

export const AVATAR_COLORS = ["#D32F2F", "#1565C0", "#2E7D32", "#6A1B9A", "#E65100", "#00695C"];

export const CURRENT_USER = {
  name: "Jean Dupont",
  role: "Conducteur de Travaux",
  email: "j.dupont@smac-sa.com",
  agence: "Agence Nantes",
};

export const AGENCES: string[] = [
  "Alsace - Bourgogne - Franche Comté",
  "Aquitaine",
  "Auralp",
  "Auvergne Rhône-Alpes - Enveloppe",
  "Bretagne",
  "Centre-Maine",
  "Gennevilliers",
  "Haut de France",
  "IDF Enveloppe",
  "IDF Etanchéité",
  "Industries",
  "Limousin Berry",
  "Lorraine - Champagne-Ardennes",
  "Normandie",
  "Occitanie",
  "Océan Indien",
  "PACA",
  "Paris",
  "Pays de Loire",
  "Poitou-Charentes",
  "SIEGE SMAC",
];

export const ETABLISSEMENTS: string[] = [
  "SMAC AIX EN PROVENCE",
  "SMAC AMIENS",
  "SMAC ANGERS",
  "SMAC ANGOULEME",
  "SMAC ANNECY",
  "SMAC Antony",
  "SMAC BAYONNE",
  "SMAC BESANCON",
  "SMAC BIOT",
  "SMAC BLOIS",
  "SMAC BORDEAUX",
  "SMAC BOURGES",
  "SMAC BREST",
  "SMAC BRIVE",
  "SMAC CHALONS SUR SAONE",
  "SMAC CHATEAUROUX",
  "SMAC CHERBOURG",
  "SMAC CLERMONT FERRAND",
  "SMAC DIJON",
  "SMAC DUNKERQUE",
  "SMAC GENNEVILLIERS",
  "SMAC GRENOBLE",
  "SMAC LA ROCHE SUR YON",
  "SMAC LA ROCHELLE",
  "SMAC LE HAVRE",
  "SMAC LE MANS",
  "SMAC LIMOGES",
  "SMAC LORIENT",
  "SMAC MAYOTTE",
  "SMAC METZ",
  "SMAC MONTPELLIER",
  "SMAC MULHOUSE",
  "SMAC NANCY",
  "SMAC NANTES",
  "SMAC NORD",
  "SMAC Normandie Caen",
  "SMAC Normandie Rouen",
  "SMAC OCEAN INDIEN",
  "SMAC ORLEANS",
  "SMAC PARIS",
  "SMAC PAU",
  "SMAC PERPIGNAN",
  "SMAC PIERRELATTE",
  "SMAC POITIERS",
  "SMAC Paris Nord 2.",
  "SMAC REIMS",
  "SMAC RENNES",
  "SMAC SAINT ETIENNE",
  "SMAC SAINT NAZAIRE",
  "SMAC SAINT PRIEST",
  "SMAC SIEGE",
  "SMAC STRASBOURG",
  "SMAC TOULOUSE",
  "SMAC TOURS",
  "SMAC TROYES",
  "SMAC VAULX EN VELIN",
  "SMAC YFFINIAC",
  "USINE LIMOGES",
  "USINE RENNES",
  "USINE SAINT PIERRE DES CORPS",
  "USINE VENISSIEUX",
];

export const INITIAL_FORM: Form = {
  agence: "",
  etablissement: "",
  chantier: "",
  zone: "",
  date: "",
  responsable: "",
};

export const INITIAL_ETAT_SURFACE: EtatSurface = {
  reg1: "SO",   reg1Photos: [],  reg1Comment: "",
  prop1: "SO",  prop1Photos: [], prop1Comment: "",
  reg2: "SO",   reg2Photos: [],  reg2Comment: "",
  prop2: "SO",  prop2Photos: [], prop2Comment: "",
};

export const INITIAL_RELEVES: Releves = {
  trous: "SO",
  remplissage: "SO",
  hauteur: "SO",
  profondeur: "SO",
  protection: "SO",
  niveaux: "SO",
};

export const INITIAL_POINTS: Points = {
  tremies: "SO",
  eaux: "SO",
  deversoirs: "SO",
  trop: "SO",
  reservations: "SO",
  joints: "SO",
  observations: "",
};

export const INITIAL_PARTICIPANT: Omit<Participant, "id"> = {
  nom: "",
  titre: "",
  signed: false,
  sigDataUrl: null,
  reception: "OUI",
  miseEnConformite: "",
  email: "",
  autoEmail: false,
};

export const INITIAL_PARTICIPANTS: Participant[] = [
  { id: 1, ...INITIAL_PARTICIPANT },
];

export const SURFACE_FIELDS: [string, string][] = [
  ["reg1", "Régularité du support (surface)"],
  ["prop1", "Propreté du support (surface)"],
  ["reg2", "Régularité du support (partie courante)"],
  ["prop2", "Propreté du support (partie courante)"],
];

export const RELEVES_FIELDS: [string, string][] = [
  ["trous", "Trous de banches rebouchés"],
  ["remplissage", "Remplissage joints panneaux préfabriqués"],
  ["hauteur", "Hauteur engravure"],
  ["profondeur", "Profondeur engravure"],
  ["protection", "Protection tête de relevés"],
  ["niveaux", "Niveaux d'arase"],
];

export const POINT_FIELDS: [string, string][] = [
  ["tremies", "Trémies lanterneaux"],
  ["eaux", "Eaux pluviales"],
  ["deversoirs", "Déversoirs"],
  ["trop", "Trop-pleins"],
  ["reservations", "Réservations sorties / pénétrations"],
  ["joints", "Joints de dilatation"],
];

export const SAMPLE_PVS: PV[] = [
  {
    id: 1,
    num: "PV #2024-0892",
    name: "Résidence Les Alizés",
    agency: "Agence Nantes",
    date: "12 Oct. 2023",
    etablissement: "Établissement Nord-Ouest",
    responsable: "M. Laurent",
    reserves: [
      {
        id: 10,
        localisation: "Toiture Nord",
        detail: "Fissure relevé",
        photos: [{ id: 20, url: "https://picsum.photos/seed/rv1/300/200" }],
      },
    ],
    etatSurface: { reg1: "Conforme", reg1Photos: [], reg1Comment: "", prop1: "SO", prop1Photos: [], prop1Comment: "", reg2: "Conforme", reg2Photos: [], reg2Comment: "", prop2: "SO", prop2Photos: [], prop2Comment: "" },
    releves: { trous: "Conforme", remplissage: "SO", hauteur: "SO", profondeur: "SO", protection: "SO", niveaux: "SO" },
    points: { tremies: "SO", eaux: "SO", deversoirs: "SO", trop: "SO", reservations: "SO", joints: "SO", observations: "" },
    participants: [{ id: 1, nom: "Jean Dupont", titre: "Conducteur de Travaux", signed: true, sigDataUrl: null, reception: "OUI", miseEnConformite: "", email: "", autoEmail: false }],
    savedRef: "PV #2024-0892",
    savedDate: "12 Oct. 2023 • 09:15",
    versions: [
      {
        id: 901,
        savedDate: "12 Oct. 2023 • 09:15",
        ref: "PV # 2024 - 0892",
        chantier: "Résidence Les Alizés",
        agency: "Agence Nantes",
        etablissement: "SMAC NANTES",
        zone: "",
        date: "12 Oct. 2023",
        responsable: "M. Laurent",
        reserves: [{ id: 10, localisation: "Toiture Nord", detail: "Fissure relevé", photos: [{ id: 20, url: "https://picsum.photos/seed/rv1/300/200" }] }],
        etatSurface: { reg1: "Conforme", reg1Photos: [], reg1Comment: "", prop1: "SO", prop1Photos: [], prop1Comment: "", reg2: "Conforme", reg2Photos: [], reg2Comment: "", prop2: "SO", prop2Photos: [], prop2Comment: "" },
        releves: { trous: "Conforme", remplissage: "SO", hauteur: "SO", profondeur: "SO", protection: "SO", niveaux: "SO" },
        points: { tremies: "SO", eaux: "SO", deversoirs: "SO", trop: "SO", reservations: "SO", joints: "SO", observations: "" },
        participants: [{ id: 1, nom: "Jean Dupont", titre: "Conducteur de Travaux", signed: true, sigDataUrl: null, reception: "OUI", miseEnConformite: "", email: "", autoEmail: false }],
      },
    ],
  },
  {
    id: 2,
    num: "PV #2024-0901",
    name: "Campus Innovation",
    agency: "Agence Rennes",
    date: "12 Oct. 2023",
    etablissement: "Établissement Ouest",
    responsable: "Mme. Bertrand",
    reserves: [],
    etatSurface: { reg1: "Non Conforme", reg1Photos: [], reg1Comment: "", prop1: "SO", prop1Photos: [], prop1Comment: "", reg2: "SO", reg2Photos: [], reg2Comment: "", prop2: "SO", prop2Photos: [], prop2Comment: "" },
    releves: { trous: "SO", remplissage: "SO", hauteur: "SO", profondeur: "SO", protection: "SO", niveaux: "SO" },
    points: { tremies: "SO", eaux: "SO", deversoirs: "SO", trop: "SO", reservations: "SO", joints: "SO", observations: "" },
    participants: [{ id: 1, nom: "Alice Martin", titre: "Ingénieure", signed: false, sigDataUrl: null, reception: "NON", miseEnConformite: "", email: "", autoEmail: false }],
    savedRef: "PV #2024-0901",
    savedDate: "12 Oct. 2023 • 14:00",
    versions: [
      {
        id: 902,
        savedDate: "12 Oct. 2023 • 14:00",
        ref: "PV # 2024 - 0901",
        chantier: "Campus Innovation",
        agency: "Agence Rennes",
        etablissement: "SMAC RENNES",
        zone: "",
        date: "12 Oct. 2023",
        responsable: "Mme. Bertrand",
        reserves: [],
        etatSurface: { reg1: "Non Conforme", reg1Photos: [], reg1Comment: "", prop1: "SO", prop1Photos: [], prop1Comment: "", reg2: "SO", reg2Photos: [], reg2Comment: "", prop2: "SO", prop2Photos: [], prop2Comment: "" },
        releves: { trous: "SO", remplissage: "SO", hauteur: "SO", profondeur: "SO", protection: "SO", niveaux: "SO" },
        points: { tremies: "SO", eaux: "SO", deversoirs: "SO", trop: "SO", reservations: "SO", joints: "SO", observations: "" },
        participants: [{ id: 1, nom: "Alice Martin", titre: "Ingénieure", signed: false, sigDataUrl: null, reception: "NON", miseEnConformite: "", email: "", autoEmail: false }],
      },
    ],
  },
  {
    id: 3,
    num: "PV #2024-0785",
    name: "Le Belvédère",
    agency: "Agence Nantes",
    date: "05 Oct. 2023",
    etablissement: "Établissement Nord-Ouest",
    responsable: "M. Lefebvre",
    reserves: [],
    etatSurface: { reg1: "SO", reg1Photos: [], reg1Comment: "", prop1: "SO", prop1Photos: [], prop1Comment: "", reg2: "SO", reg2Photos: [], reg2Comment: "", prop2: "SO", prop2Photos: [], prop2Comment: "" },
    releves: { trous: "SO", remplissage: "SO", hauteur: "SO", profondeur: "SO", protection: "SO", niveaux: "SO" },
    points: { tremies: "SO", eaux: "SO", deversoirs: "SO", trop: "SO", reservations: "SO", joints: "SO", observations: "" },
    participants: [{ id: 1, nom: "Paul Moreau", titre: "Chef de chantier", signed: true, sigDataUrl: null, reception: "OUI", miseEnConformite: "", email: "", autoEmail: false }],
    savedRef: "PV #2024-0785",
    savedDate: "05 Oct. 2023 • 11:30",
    versions: [],
  },
  {
    id: 4,
    num: "PV #2024-0912",
    name: "Entrepôt LogiSud",
    agency: "Agence Bordeaux",
    date: "Ce matin",
    etablissement: "Établissement Sud-Ouest",
    responsable: "Mme. Rousseau",
    reserves: [],
    etatSurface: { reg1: "SO", reg1Photos: [], reg1Comment: "", prop1: "SO", prop1Photos: [], prop1Comment: "", reg2: "SO", reg2Photos: [], reg2Comment: "", prop2: "SO", prop2Photos: [], prop2Comment: "" },
    releves: { trous: "SO", remplissage: "SO", hauteur: "SO", profondeur: "SO", protection: "SO", niveaux: "SO" },
    points: { tremies: "SO", eaux: "SO", deversoirs: "SO", trop: "SO", reservations: "SO", joints: "SO", observations: "" },
    participants: [{ id: 1, nom: "Sophie Blanc", titre: "Ingénieure Travaux", signed: false, sigDataUrl: null, reception: "OUI", miseEnConformite: "", email: "", autoEmail: false }],
    savedRef: "PV #2024-0912",
    savedDate: "Aujourd'hui • 08:45",
    versions: [],
  },
];
